#!/bin/sh
#
# Update language definitions from OpenTTD SVN
#

STABLEDIR="stable_languages"
UNSTABLEDIR="unstable_languages"

GITURL="https://github.com/OpenTTD/OpenTTD.git"
WORKDIR="openttd"



if [ -d ${WORKDIR} ]
then env GIT_DIR=${WORKDIR}/.git GIT_WORK_TREE=${WORKDIR} git pull --depth 1
else git clone --depth 1 ${GITURL} ${WORKDIR}
fi

echo "Checking stable languages"
scripts/filter_update_langs ${WORKDIR}/src/lang ${STABLEDIR}

echo "Checking unstable languages"
scripts/filter_update_langs ${WORKDIR}/src/lang/unfinished ${UNSTABLEDIR}
