name: Commit checker

on:
  pull_request:

jobs:
  commit-checker:
    name: Commit checker
    runs-on: ubuntu-latest

    steps:
    - uses: TrueBrain/OpenTTD-actions/workflow-commit-checker@workflows
